name: Website
on: push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get common episodes
        run: |
          git clone https://github.com/enibigir/hsf-training-cicd-basics-webpage.git common
          cp common/_episodes/*.md _episodes/
          rm -rf common

      - name: Build
        run: |
          docker run --rm \
          --volume="${{ github.workspace }}:/srv/jekyll" \
          jekyll/builder:latest /bin/bash -c "gem install bundler && \
          chmod -R 777 /srv/jekyll && \
          bundle install && \
          bundle exec jekyll build --trace"
